[2020-09-15T11:30:22.744] [ERROR] errorLogger - 
*************** error log start ***************
request method: PUT
request originalUrl:  /api/white/whiteStopMail
request client ip:  ::ffff:127.0.0.1
request body: 
{"id":11,"gameid":"1"}
response time: 1600140622743
err name: Error
err message: 此邮件有白名单用户存在！！！
err stack: Error: 此邮件有白名单用户存在！！！
    at _callee4$ (H:\fancyguo-gm\server\src\app\service\/white.js:81:10)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
*************** error log end ***************

[2020-09-15T11:30:55.823] [ERROR] errorLogger - 
*************** error log start ***************
request method: PUT
request originalUrl:  /api/white/whiteStopMail
request client ip:  ::ffff:127.0.0.1
request body: 
{"id":11,"gameid":"1"}
response time: 1600140655823
err name: Error
err message: 此邮件有白名单用户存在！！！
err stack: Error: 此邮件有白名单用户存在！！！
    at _callee4$ (H:\fancyguo-gm\server\src\app\service\/white.js:81:10)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
*************** error log end ***************

[2020-09-15T11:33:02.126] [ERROR] errorLogger - 
*************** error log start ***************
request method: PUT
request originalUrl:  /api/white/whiteStopMail
request client ip:  ::ffff:127.0.0.1
request body: 
{"id":12,"gameid":"1"}
response time: 1600140782125
err name: Error
err message: 此邮件有白名单用户存在！！！
err stack: Error: 此邮件有白名单用户存在！！！
    at _callee4$ (H:\fancyguo-gm\server\src\app\service\/white.js:82:10)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
*************** error log end ***************

[2020-09-15T11:33:32.903] [ERROR] errorLogger - 
*************** error log start ***************
request method: PUT
request originalUrl:  /api/white/whiteStopMail
request client ip:  ::ffff:127.0.0.1
request body: 
{"id":12,"gameid":"1"}
response time: 1600140812903
err name: Error
err message: 此邮件有白名单用户存在！！！
err stack: Error: 此邮件有白名单用户存在！！！
    at _callee4$ (H:\fancyguo-gm\server\src\app\service\/white.js:82:10)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
*************** error log end ***************

[2020-09-15T11:34:59.426] [ERROR] errorLogger - 
*************** error log start ***************
request method: PUT
request originalUrl:  /api/white/whiteStopMail
request client ip:  ::ffff:127.0.0.1
request body: 
{"id":12,"gameid":"1"}
response time: 1600140899426
err name: Error
err message: 此邮件有白名单用户存在！！！
err stack: Error: 此邮件有白名单用户存在！！！
    at _callee4$ (H:\fancyguo-gm\server\src\app\service\/white.js:82:10)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
*************** error log end ***************

[2020-09-15T11:35:58.416] [ERROR] errorLogger - 
*************** error log start ***************
request method: PUT
request originalUrl:  /api/white/whiteStopMail
request client ip:  ::ffff:127.0.0.1
request body: 
{"id":12,"gameid":"1"}
response time: 1600140958416
err name: Error
err message: 此邮件有白名单用户存在！！！
err stack: Error: 此邮件有白名单用户存在！！！
    at _callee4$ (H:\fancyguo-gm\server\src\app\service\/white.js:82:10)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
*************** error log end ***************

[2020-09-15T11:36:09.568] [ERROR] errorLogger - 
*************** error log start ***************
request method: PUT
request originalUrl:  /api/white/whiteStopMail
request client ip:  ::ffff:127.0.0.1
request body: 
{"id":12,"gameid":"1"}
response time: 1600140969568
err name: Error
err message: 此邮件有白名单用户存在！！！
err stack: Error: 此邮件有白名单用户存在！！！
    at _callee4$ (H:\fancyguo-gm\server\src\app\service\/white.js:82:10)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
*************** error log end ***************

[2020-09-15T11:36:34.635] [ERROR] errorLogger - 
*************** error log start ***************
request method: PUT
request originalUrl:  /api/white/whiteStopMail
request client ip:  ::ffff:127.0.0.1
request body: 
{"id":12,"gameid":"1"}
response time: 1600140994635
err name: Error
err message: 此邮件有白名单用户存在！！！
err stack: Error: 此邮件有白名单用户存在！！！
    at _callee4$ (H:\fancyguo-gm\server\src\app\service\/white.js:82:10)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
*************** error log end ***************

[2020-09-15T11:37:02.937] [ERROR] errorLogger - 
*************** error log start ***************
request method: PUT
request originalUrl:  /api/white/whiteStopMail
request client ip:  ::ffff:127.0.0.1
request body: 
{"id":12,"gameid":"1"}
response time: 1600141022937
err name: Error
err message: 此邮件有白名单用户存在！！！
err stack: Error: 此邮件有白名单用户存在！！！
    at _callee4$ (H:\fancyguo-gm\server\src\app\service\/white.js:82:10)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
*************** error log end ***************

[2020-09-15T11:37:10.157] [ERROR] errorLogger - 
*************** error log start ***************
request method: PUT
request originalUrl:  /api/white/whiteStopMail
request client ip:  ::ffff:127.0.0.1
request body: 
{"id":12,"gameid":"1"}
response time: 1600141030157
err name: Error
err message: 此邮件有白名单用户存在！！！
err stack: Error: 此邮件有白名单用户存在！！！
    at _callee4$ (H:\fancyguo-gm\server\src\app\service\/white.js:82:10)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
*************** error log end ***************

[2020-09-15T11:37:20.792] [ERROR] errorLogger - 
*************** error log start ***************
request method: PUT
request originalUrl:  /api/white/whiteStopMail
request client ip:  ::ffff:127.0.0.1
request body: 
{"id":12,"gameid":"1"}
response time: 1600141040792
err name: Error
err message: 此邮件有白名单用户存在！！！
err stack: Error: 此邮件有白名单用户存在！！！
    at _callee4$ (H:\fancyguo-gm\server\src\app\service\/white.js:82:10)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
*************** error log end ***************

[2020-09-15T11:39:30.471] [ERROR] errorLogger - 
*************** error log start ***************
request method: PUT
request originalUrl:  /api/white/whiteStopMail
request client ip:  ::ffff:127.0.0.1
request body: 
{"id":12,"gameid":"1"}
response time: 1600141170470
err name: Error
err message: 此邮件有白名单用户存在！！！
err stack: Error: 此邮件有白名单用户存在！！！
    at _callee4$ (H:\fancyguo-gm\server\src\app\service\/white.js:80:10)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
*************** error log end ***************

[2020-09-15T14:09:40.900] [ERROR] errorLogger - 
*************** error log start ***************
request method: PUT
request originalUrl:  /api/white/whiteStopMail
request client ip:  ::ffff:127.0.0.1
request body: 
{"id":13,"gameid":"1"}
response time: 1600150180899
err name: Error
err message: 此邮件有白名单用户存在！！！
err stack: Error: 此邮件有白名单用户存在！！！
    at _callee4$ (H:\fancyguo-gm\server\src\app\service\/white.js:80:10)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
*************** error log end ***************

[2020-09-15T14:19:56.172] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/white/whiteFindAll?value=%7B%22id%22:6%7D&type=&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"value":"{\"id\":6}","type":"","page":"1","pagesize":"10","gameid":"1"}
response time: 1600150796172
err name: SequelizeDatabaseError
err message: 无效的整数类型输入语法: "{"id":6}"
err stack: SequelizeDatabaseError: 无效的整数类型输入语法: "{"id":6}"
    at Query.formatError (H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
From previous event:
    at Query.run (H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:64:23)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:29
From previous event:
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:12
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:651:10
    at H:\fancyguo-gm\server\node_modules\retry-as-promised\index.js:70:21
    at new Promise (<anonymous>)
    at retryAsPromised (H:\fancyguo-gm\server\node_modules\retry-as-promised\index.js:60:10)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:641:30
From previous event:
    at Sequelize.query (H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:590:23)
    at _callee2$ (H:\fancyguo-gm\server\src\app\service\/white.js:47:31)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at whiteServer.<anonymous> (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at whiteServer.whiteFindAll (H:\fancyguo-gm\server\src\app\service\white.js:153:30)
    at _callee2$ (H:\fancyguo-gm\server\src\app\controllers\/white.js:22:33)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at whiteFindAll (H:\fancyguo-gm\server\src\app\controllers\white.js:110:30)
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:45:18)
    at H:\fancyguo-gm\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at H:\fancyguo-gm\server\node_modules\koa-compose\index.js:36:12
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-router\lib\router.js:351:31)
    at next (H:\fancyguo-gm\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at _callee$ (H:\fancyguo-gm\server\src\middleware\/index.js:48:11)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at H:\fancyguo-gm\server\src\middleware\/index.js:43:2
*************** error log end ***************

[2020-09-15T14:20:07.085] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/white/whiteFindAll?value=%7B%22id%22:6%7D&type=&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"value":"{\"id\":6}","type":"","page":"1","pagesize":"10","gameid":"1"}
response time: 1600150807085
err name: SequelizeDatabaseError
err message: 无效的整数类型输入语法: "{"id":6}"
err stack: SequelizeDatabaseError: 无效的整数类型输入语法: "{"id":6}"
    at Query.formatError (H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
From previous event:
    at Query.run (H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:64:23)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:29
From previous event:
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:12
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:651:10
    at H:\fancyguo-gm\server\node_modules\retry-as-promised\index.js:70:21
    at new Promise (<anonymous>)
    at retryAsPromised (H:\fancyguo-gm\server\node_modules\retry-as-promised\index.js:60:10)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:641:30
From previous event:
    at Sequelize.query (H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:590:23)
    at _callee2$ (H:\fancyguo-gm\server\src\app\service\/white.js:47:31)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at whiteServer.<anonymous> (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at whiteServer.whiteFindAll (H:\fancyguo-gm\server\src\app\service\white.js:153:30)
    at _callee2$ (H:\fancyguo-gm\server\src\app\controllers\/white.js:22:33)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at whiteFindAll (H:\fancyguo-gm\server\src\app\controllers\white.js:110:30)
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:45:18)
    at H:\fancyguo-gm\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at H:\fancyguo-gm\server\node_modules\koa-compose\index.js:36:12
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-router\lib\router.js:351:31)
    at next (H:\fancyguo-gm\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at _callee$ (H:\fancyguo-gm\server\src\middleware\/index.js:48:11)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at H:\fancyguo-gm\server\src\middleware\/index.js:43:2
*************** error log end ***************

[2020-09-15T16:08:43.499] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/white/recordLookup?key=roleid&value=&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"key":"roleid","value":"","page":"1","pagesize":"10","gameid":"1"}
response time: 1600157323499
err name: SequelizeDatabaseError
err message: 字段 "asd.create_time" 必须出现在 GROUP BY 子句中或者在聚合函数中使用
err stack: SequelizeDatabaseError: 字段 "asd.create_time" 必须出现在 GROUP BY 子句中或者在聚合函数中使用
    at Query.formatError (H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
From previous event:
    at Query.run (H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:64:23)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:29
From previous event:
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:12
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:651:10
    at H:\fancyguo-gm\server\node_modules\retry-as-promised\index.js:70:21
    at new Promise (<anonymous>)
    at retryAsPromised (H:\fancyguo-gm\server\node_modules\retry-as-promised\index.js:60:10)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:641:30
From previous event:
    at Sequelize.query (H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:590:23)
    at _callee13$ (H:\fancyguo-gm\server\src\app\service\/white.js:234:33)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
*************** error log end ***************

[2020-09-15T20:01:50.194] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/client/find?isShowType=1&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"isShowType":"1","page":"1","pagesize":"10","gameid":"1"}
response time: 1600171310193
err name: SequelizeDatabaseError
err message: 操作符不存在: character varying = integer
err stack: SequelizeDatabaseError: 操作符不存在: character varying = integer
    at Query.formatError (H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
From previous event:
    at Query.run (H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:64:23)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:29
From previous event:
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:12
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:651:10
    at H:\fancyguo-gm\server\node_modules\retry-as-promised\index.js:70:21
    at new Promise (<anonymous>)
    at retryAsPromised (H:\fancyguo-gm\server\node_modules\retry-as-promised\index.js:60:10)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:641:30
From previous event:
    at Sequelize.query (H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:590:23)
    at _callee2$ (H:\fancyguo-gm\server\src\app\service\/client.js:32:31)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at clientService.<anonymous> (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at clientService.find (H:\fancyguo-gm\server\src\app\service\client.js:110:22)
    at _callee2$ (H:\fancyguo-gm\server\src\app\controllers\/client.js:20:36)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at find (H:\fancyguo-gm\server\src\app\controllers\client.js:109:22)
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:45:18)
    at H:\fancyguo-gm\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at H:\fancyguo-gm\server\node_modules\koa-compose\index.js:36:12
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-router\lib\router.js:351:31)
    at next (H:\fancyguo-gm\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at _callee$ (H:\fancyguo-gm\server\src\middleware\/index.js:48:11)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at H:\fancyguo-gm\server\src\middleware\/index.js:43:2
*************** error log end ***************

[2020-09-15T20:02:06.669] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/client/find?isShowType=&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"isShowType":"","page":"1","pagesize":"10","gameid":"1"}
response time: 1600171326669
err name: SequelizeDatabaseError
err message: 操作符不存在: character varying = integer
err stack: SequelizeDatabaseError: 操作符不存在: character varying = integer
    at Query.formatError (H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
From previous event:
    at Query.run (H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:64:23)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:29
From previous event:
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:12
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:651:10
    at H:\fancyguo-gm\server\node_modules\retry-as-promised\index.js:70:21
    at new Promise (<anonymous>)
    at retryAsPromised (H:\fancyguo-gm\server\node_modules\retry-as-promised\index.js:60:10)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:641:30
From previous event:
    at Sequelize.query (H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:590:23)
    at _callee2$ (H:\fancyguo-gm\server\src\app\service\/client.js:40:31)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at clientService.<anonymous> (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at clientService.find (H:\fancyguo-gm\server\src\app\service\client.js:122:22)
    at _callee2$ (H:\fancyguo-gm\server\src\app\controllers\/client.js:20:36)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at find (H:\fancyguo-gm\server\src\app\controllers\client.js:109:22)
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:45:18)
    at H:\fancyguo-gm\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at H:\fancyguo-gm\server\node_modules\koa-compose\index.js:36:12
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-router\lib\router.js:351:31)
    at next (H:\fancyguo-gm\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at _callee$ (H:\fancyguo-gm\server\src\middleware\/index.js:48:11)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at H:\fancyguo-gm\server\src\middleware\/index.js:43:2
*************** error log end ***************

[2020-09-15T20:03:53.181] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/client/find?isShowType=1&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"isShowType":"1","page":"1","pagesize":"10","gameid":"1"}
response time: 1600171433180
err name: SequelizeDatabaseError
err message: invalid input syntax for type json
err stack: SequelizeDatabaseError: invalid input syntax for type json
    at Query.formatError (H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
From previous event:
    at Query.run (H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:64:23)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:29
From previous event:
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:12
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:651:10
    at H:\fancyguo-gm\server\node_modules\retry-as-promised\index.js:70:21
    at new Promise (<anonymous>)
    at retryAsPromised (H:\fancyguo-gm\server\node_modules\retry-as-promised\index.js:60:10)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:641:30
From previous event:
    at Sequelize.query (H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:590:23)
    at _callee2$ (H:\fancyguo-gm\server\src\app\service\/client.js:40:31)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at clientService.<anonymous> (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at clientService.find (H:\fancyguo-gm\server\src\app\service\client.js:123:22)
    at _callee2$ (H:\fancyguo-gm\server\src\app\controllers\/client.js:20:36)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at find (H:\fancyguo-gm\server\src\app\controllers\client.js:109:22)
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:45:18)
    at H:\fancyguo-gm\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at H:\fancyguo-gm\server\node_modules\koa-compose\index.js:36:12
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-router\lib\router.js:351:31)
    at next (H:\fancyguo-gm\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at _callee$ (H:\fancyguo-gm\server\src\middleware\/index.js:48:11)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at H:\fancyguo-gm\server\src\middleware\/index.js:43:2
*************** error log end ***************

[2020-09-15T20:03:59.073] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/client/find?isShowType=2&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"isShowType":"2","page":"1","pagesize":"10","gameid":"1"}
response time: 1600171439073
err name: SequelizeDatabaseError
err message: invalid input syntax for type json
err stack: SequelizeDatabaseError: invalid input syntax for type json
    at Query.formatError (H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
From previous event:
    at Query.run (H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:64:23)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:29
From previous event:
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:12
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:651:10
    at H:\fancyguo-gm\server\node_modules\retry-as-promised\index.js:70:21
    at new Promise (<anonymous>)
    at retryAsPromised (H:\fancyguo-gm\server\node_modules\retry-as-promised\index.js:60:10)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:641:30
From previous event:
    at Sequelize.query (H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:590:23)
    at _callee2$ (H:\fancyguo-gm\server\src\app\service\/client.js:40:31)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at clientService.<anonymous> (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at clientService.find (H:\fancyguo-gm\server\src\app\service\client.js:123:22)
    at _callee2$ (H:\fancyguo-gm\server\src\app\controllers\/client.js:20:36)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at find (H:\fancyguo-gm\server\src\app\controllers\client.js:109:22)
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:45:18)
    at H:\fancyguo-gm\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at H:\fancyguo-gm\server\node_modules\koa-compose\index.js:36:12
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-router\lib\router.js:351:31)
    at next (H:\fancyguo-gm\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at _callee$ (H:\fancyguo-gm\server\src\middleware\/index.js:48:11)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at H:\fancyguo-gm\server\src\middleware\/index.js:43:2
*************** error log end ***************

[2020-09-15T20:04:05.502] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/client/find?isShowType=1&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"isShowType":"1","page":"1","pagesize":"10","gameid":"1"}
response time: 1600171445501
err name: SequelizeDatabaseError
err message: invalid input syntax for type json
err stack: SequelizeDatabaseError: invalid input syntax for type json
    at Query.formatError (H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
From previous event:
    at Query.run (H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:64:23)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:29
From previous event:
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:12
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:651:10
    at H:\fancyguo-gm\server\node_modules\retry-as-promised\index.js:70:21
    at new Promise (<anonymous>)
    at retryAsPromised (H:\fancyguo-gm\server\node_modules\retry-as-promised\index.js:60:10)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:641:30
From previous event:
    at Sequelize.query (H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:590:23)
    at _callee2$ (H:\fancyguo-gm\server\src\app\service\/client.js:40:31)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at clientService.<anonymous> (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at clientService.find (H:\fancyguo-gm\server\src\app\service\client.js:123:22)
    at _callee2$ (H:\fancyguo-gm\server\src\app\controllers\/client.js:20:36)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at find (H:\fancyguo-gm\server\src\app\controllers\client.js:109:22)
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:45:18)
    at H:\fancyguo-gm\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at H:\fancyguo-gm\server\node_modules\koa-compose\index.js:36:12
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-router\lib\router.js:351:31)
    at next (H:\fancyguo-gm\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at _callee$ (H:\fancyguo-gm\server\src\middleware\/index.js:48:11)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at H:\fancyguo-gm\server\src\middleware\/index.js:43:2
*************** error log end ***************

[2020-09-15T20:04:16.504] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/client/find?isShowType[]=%E6%B5%8B%E8%AF%95&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"isShowType[]":"测试","page":"1","pagesize":"10","isShowType":"测试","gameid":"1"}
response time: 1600171456504
err name: SequelizeDatabaseError
err message: invalid input syntax for type json
err stack: SequelizeDatabaseError: invalid input syntax for type json
    at Query.formatError (H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
From previous event:
    at Query.run (H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:64:23)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:29
From previous event:
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:12
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:651:10
    at H:\fancyguo-gm\server\node_modules\retry-as-promised\index.js:70:21
    at new Promise (<anonymous>)
    at retryAsPromised (H:\fancyguo-gm\server\node_modules\retry-as-promised\index.js:60:10)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:641:30
From previous event:
    at Sequelize.query (H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:590:23)
    at _callee2$ (H:\fancyguo-gm\server\src\app\service\/client.js:40:31)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at clientService.<anonymous> (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at clientService.find (H:\fancyguo-gm\server\src\app\service\client.js:123:22)
    at _callee2$ (H:\fancyguo-gm\server\src\app\controllers\/client.js:20:36)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at find (H:\fancyguo-gm\server\src\app\controllers\client.js:109:22)
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:45:18)
    at H:\fancyguo-gm\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at H:\fancyguo-gm\server\node_modules\koa-compose\index.js:36:12
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-router\lib\router.js:351:31)
    at next (H:\fancyguo-gm\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at _callee$ (H:\fancyguo-gm\server\src\middleware\/index.js:48:11)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at H:\fancyguo-gm\server\src\middleware\/index.js:43:2
*************** error log end ***************

[2020-09-15T20:04:25.094] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/client/find?isShowType[]=%E6%B5%8B%E8%AF%95&isShowType[]=%E6%AD%A3%E5%BC%8F&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"isShowType[]":["测试","正式"],"page":"1","pagesize":"10","isShowType":["测试","正式"],"gameid":"1"}
response time: 1600171465093
err name: SequelizeDatabaseError
err message: invalid input syntax for type json
err stack: SequelizeDatabaseError: invalid input syntax for type json
    at Query.formatError (H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
From previous event:
    at Query.run (H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:64:23)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:29
From previous event:
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:12
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:651:10
    at H:\fancyguo-gm\server\node_modules\retry-as-promised\index.js:70:21
    at new Promise (<anonymous>)
    at retryAsPromised (H:\fancyguo-gm\server\node_modules\retry-as-promised\index.js:60:10)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:641:30
From previous event:
    at Sequelize.query (H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:590:23)
    at _callee2$ (H:\fancyguo-gm\server\src\app\service\/client.js:40:31)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at clientService.<anonymous> (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at clientService.find (H:\fancyguo-gm\server\src\app\service\client.js:123:22)
    at _callee2$ (H:\fancyguo-gm\server\src\app\controllers\/client.js:20:36)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at find (H:\fancyguo-gm\server\src\app\controllers\client.js:109:22)
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:45:18)
    at H:\fancyguo-gm\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at H:\fancyguo-gm\server\node_modules\koa-compose\index.js:36:12
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-router\lib\router.js:351:31)
    at next (H:\fancyguo-gm\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at _callee$ (H:\fancyguo-gm\server\src\middleware\/index.js:48:11)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at H:\fancyguo-gm\server\src\middleware\/index.js:43:2
*************** error log end ***************

[2020-09-15T20:04:30.079] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/client/find?isShowType[]=%E6%B5%8B%E8%AF%95&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"isShowType[]":"测试","page":"1","pagesize":"10","isShowType":"测试","gameid":"1"}
response time: 1600171470079
err name: SequelizeDatabaseError
err message: invalid input syntax for type json
err stack: SequelizeDatabaseError: invalid input syntax for type json
    at Query.formatError (H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
From previous event:
    at Query.run (H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:64:23)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:29
From previous event:
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:12
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:651:10
    at H:\fancyguo-gm\server\node_modules\retry-as-promised\index.js:70:21
    at new Promise (<anonymous>)
    at retryAsPromised (H:\fancyguo-gm\server\node_modules\retry-as-promised\index.js:60:10)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:641:30
From previous event:
    at Sequelize.query (H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:590:23)
    at _callee2$ (H:\fancyguo-gm\server\src\app\service\/client.js:40:31)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at clientService.<anonymous> (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at clientService.find (H:\fancyguo-gm\server\src\app\service\client.js:123:22)
    at _callee2$ (H:\fancyguo-gm\server\src\app\controllers\/client.js:20:36)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at find (H:\fancyguo-gm\server\src\app\controllers\client.js:109:22)
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:45:18)
    at H:\fancyguo-gm\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at H:\fancyguo-gm\server\node_modules\koa-compose\index.js:36:12
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-router\lib\router.js:351:31)
    at next (H:\fancyguo-gm\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at _callee$ (H:\fancyguo-gm\server\src\middleware\/index.js:48:11)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at H:\fancyguo-gm\server\src\middleware\/index.js:43:2
*************** error log end ***************

[2020-09-15T20:04:32.094] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/client/find?isShowType[]=%E6%B5%8B%E8%AF%95&isShowType[]=%E6%AD%A3%E5%BC%8F&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"isShowType[]":["测试","正式"],"page":"1","pagesize":"10","isShowType":["测试","正式"],"gameid":"1"}
response time: 1600171472094
err name: SequelizeDatabaseError
err message: invalid input syntax for type json
err stack: SequelizeDatabaseError: invalid input syntax for type json
    at Query.formatError (H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
From previous event:
    at Query.run (H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:64:23)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:29
From previous event:
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:12
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:651:10
    at H:\fancyguo-gm\server\node_modules\retry-as-promised\index.js:70:21
    at new Promise (<anonymous>)
    at retryAsPromised (H:\fancyguo-gm\server\node_modules\retry-as-promised\index.js:60:10)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:641:30
From previous event:
    at Sequelize.query (H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:590:23)
    at _callee2$ (H:\fancyguo-gm\server\src\app\service\/client.js:40:31)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at clientService.<anonymous> (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at clientService.find (H:\fancyguo-gm\server\src\app\service\client.js:123:22)
    at _callee2$ (H:\fancyguo-gm\server\src\app\controllers\/client.js:20:36)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at find (H:\fancyguo-gm\server\src\app\controllers\client.js:109:22)
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:45:18)
    at H:\fancyguo-gm\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at H:\fancyguo-gm\server\node_modules\koa-compose\index.js:36:12
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-router\lib\router.js:351:31)
    at next (H:\fancyguo-gm\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at _callee$ (H:\fancyguo-gm\server\src\middleware\/index.js:48:11)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at H:\fancyguo-gm\server\src\middleware\/index.js:43:2
*************** error log end ***************

[2020-09-15T20:04:33.375] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/client/find?isShowType[]=%E6%B5%8B%E8%AF%95&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"isShowType[]":"测试","page":"1","pagesize":"10","isShowType":"测试","gameid":"1"}
response time: 1600171473375
err name: SequelizeDatabaseError
err message: invalid input syntax for type json
err stack: SequelizeDatabaseError: invalid input syntax for type json
    at Query.formatError (H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
From previous event:
    at Query.run (H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:64:23)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:29
From previous event:
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:12
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:651:10
    at H:\fancyguo-gm\server\node_modules\retry-as-promised\index.js:70:21
    at new Promise (<anonymous>)
    at retryAsPromised (H:\fancyguo-gm\server\node_modules\retry-as-promised\index.js:60:10)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:641:30
From previous event:
    at Sequelize.query (H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:590:23)
    at _callee2$ (H:\fancyguo-gm\server\src\app\service\/client.js:40:31)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at clientService.<anonymous> (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at clientService.find (H:\fancyguo-gm\server\src\app\service\client.js:123:22)
    at _callee2$ (H:\fancyguo-gm\server\src\app\controllers\/client.js:20:36)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at find (H:\fancyguo-gm\server\src\app\controllers\client.js:109:22)
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:45:18)
    at H:\fancyguo-gm\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at H:\fancyguo-gm\server\node_modules\koa-compose\index.js:36:12
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-router\lib\router.js:351:31)
    at next (H:\fancyguo-gm\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at _callee$ (H:\fancyguo-gm\server\src\middleware\/index.js:48:11)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at H:\fancyguo-gm\server\src\middleware\/index.js:43:2
*************** error log end ***************

[2020-09-15T20:05:00.290] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/client/find?plaform=&channel=&isShowType[]=%E6%B5%8B%E8%AF%95&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"plaform":"","channel":"","isShowType[]":"测试","page":"1","pagesize":"10","isShowType":"测试","gameid":"1"}
response time: 1600171500289
err name: SequelizeDatabaseError
err message: 字段 "isshowtype" 不存在
err stack: SequelizeDatabaseError: 字段 "isshowtype" 不存在
    at Query.formatError (H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
From previous event:
    at Query.run (H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:64:23)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:29
From previous event:
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:12
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:651:10
    at H:\fancyguo-gm\server\node_modules\retry-as-promised\index.js:70:21
    at new Promise (<anonymous>)
    at retryAsPromised (H:\fancyguo-gm\server\node_modules\retry-as-promised\index.js:60:10)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:641:30
From previous event:
    at Sequelize.query (H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:590:23)
    at _callee2$ (H:\fancyguo-gm\server\src\app\service\/client.js:40:31)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at clientService.<anonymous> (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at clientService.find (H:\fancyguo-gm\server\src\app\service\client.js:122:22)
    at _callee2$ (H:\fancyguo-gm\server\src\app\controllers\/client.js:20:36)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at find (H:\fancyguo-gm\server\src\app\controllers\client.js:109:22)
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:45:18)
    at H:\fancyguo-gm\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at H:\fancyguo-gm\server\node_modules\koa-compose\index.js:36:12
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-router\lib\router.js:351:31)
    at next (H:\fancyguo-gm\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at _callee$ (H:\fancyguo-gm\server\src\middleware\/index.js:48:11)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at H:\fancyguo-gm\server\src\middleware\/index.js:43:2
*************** error log end ***************

[2020-09-15T20:22:14.787] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/client/find?plaform=&channel=&isShowType=&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"plaform":"","channel":"","isShowType":"","page":"1","pagesize":"10","gameid":"1"}
response time: 1600172534786
err name: SequelizeDatabaseError
err message: 语法错误 在 "as" 或附近的
err stack: SequelizeDatabaseError: 语法错误 在 "as" 或附近的
    at Query.formatError (H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
From previous event:
    at Query.run (H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:64:23)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:29
From previous event:
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:12
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:651:10
    at H:\fancyguo-gm\server\node_modules\retry-as-promised\index.js:70:21
    at new Promise (<anonymous>)
    at retryAsPromised (H:\fancyguo-gm\server\node_modules\retry-as-promised\index.js:60:10)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:641:30
From previous event:
    at Sequelize.query (H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:590:23)
    at _callee2$ (H:\fancyguo-gm\server\src\app\service\/client.js:43:31)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at clientService.<anonymous> (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at clientService.find (H:\fancyguo-gm\server\src\app\service\client.js:126:22)
    at _callee2$ (H:\fancyguo-gm\server\src\app\controllers\/client.js:20:36)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at find (H:\fancyguo-gm\server\src\app\controllers\client.js:109:22)
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:45:18)
    at H:\fancyguo-gm\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at H:\fancyguo-gm\server\node_modules\koa-compose\index.js:36:12
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-router\lib\router.js:351:31)
    at next (H:\fancyguo-gm\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at _callee$ (H:\fancyguo-gm\server\src\middleware\/index.js:48:11)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at H:\fancyguo-gm\server\src\middleware\/index.js:43:2
*************** error log end ***************

[2020-09-15T20:22:16.634] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/client/find?plaform=&channel=&isShowType=&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"plaform":"","channel":"","isShowType":"","page":"1","pagesize":"10","gameid":"1"}
response time: 1600172536634
err name: SequelizeDatabaseError
err message: 语法错误 在 "as" 或附近的
err stack: SequelizeDatabaseError: 语法错误 在 "as" 或附近的
    at Query.formatError (H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
From previous event:
    at Query.run (H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:64:23)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:29
From previous event:
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:12
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:651:10
    at H:\fancyguo-gm\server\node_modules\retry-as-promised\index.js:70:21
    at new Promise (<anonymous>)
    at retryAsPromised (H:\fancyguo-gm\server\node_modules\retry-as-promised\index.js:60:10)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:641:30
From previous event:
    at Sequelize.query (H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:590:23)
    at _callee2$ (H:\fancyguo-gm\server\src\app\service\/client.js:43:31)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at clientService.<anonymous> (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at clientService.find (H:\fancyguo-gm\server\src\app\service\client.js:126:22)
    at _callee2$ (H:\fancyguo-gm\server\src\app\controllers\/client.js:20:36)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at find (H:\fancyguo-gm\server\src\app\controllers\client.js:109:22)
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:45:18)
    at H:\fancyguo-gm\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at H:\fancyguo-gm\server\node_modules\koa-compose\index.js:36:12
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-router\lib\router.js:351:31)
    at next (H:\fancyguo-gm\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at _callee$ (H:\fancyguo-gm\server\src\middleware\/index.js:48:11)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at H:\fancyguo-gm\server\src\middleware\/index.js:43:2
*************** error log end ***************

[2020-09-15T21:09:08.078] [ERROR] errorLogger - 
*************** error log start ***************
request method: DELETE
request originalUrl:  /api/client/stopClient?id=17
request client ip:  ::ffff:127.0.0.1
request body: 
{"gameid":"1"}
response time: 1600175348078
err name: TypeError
err message: Cannot read property 'id' of undefined
err stack: TypeError: Cannot read property 'id' of undefined
    at _callee5$ (H:\fancyguo-gm\server\src\app\service\/client.js:75:68)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at clientService.<anonymous> (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at clientService.stopClient (H:\fancyguo-gm\server\src\app\service\client.js:232:28)
    at _callee5$ (H:\fancyguo-gm\server\src\app\controllers\/client.js:41:39)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at stopClient (H:\fancyguo-gm\server\src\app\controllers\client.js:205:28)
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:45:18)
    at H:\fancyguo-gm\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at H:\fancyguo-gm\server\node_modules\koa-compose\index.js:36:12
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-router\lib\router.js:351:31)
    at next (H:\fancyguo-gm\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at _callee$ (H:\fancyguo-gm\server\src\middleware\/index.js:48:11)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
*************** error log end ***************

[2020-09-15T21:09:53.395] [ERROR] errorLogger - 
*************** error log start ***************
request method: DELETE
request originalUrl:  /api/client/stopClient?id=17
request client ip:  ::ffff:127.0.0.1
request body: 
{"gameid":"1"}
response time: 1600175393394
err name: TypeError
err message: Cannot read property 'id' of undefined
err stack: TypeError: Cannot read property 'id' of undefined
    at _callee5$ (H:\fancyguo-gm\server\src\app\service\/client.js:76:68)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at clientService.<anonymous> (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at clientService.stopClient (H:\fancyguo-gm\server\src\app\service\client.js:233:28)
    at _callee5$ (H:\fancyguo-gm\server\src\app\controllers\/client.js:41:39)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at stopClient (H:\fancyguo-gm\server\src\app\controllers\client.js:205:28)
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:45:18)
    at H:\fancyguo-gm\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at H:\fancyguo-gm\server\node_modules\koa-compose\index.js:36:12
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-router\lib\router.js:351:31)
    at next (H:\fancyguo-gm\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at _callee$ (H:\fancyguo-gm\server\src\middleware\/index.js:48:11)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
*************** error log end ***************

[2020-09-15T21:10:26.767] [ERROR] errorLogger - 
*************** error log start ***************
request method: DELETE
request originalUrl:  /api/client/stopClient?id=17
request client ip:  ::ffff:127.0.0.1
request body: 
{"gameid":"1"}
response time: 1600175426766
err name: SequelizeDatabaseError
err message: 字段 "gameid" 不存在
err stack: SequelizeDatabaseError: 字段 "gameid" 不存在
    at Query.formatError (H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
From previous event:
    at Query.run (H:\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:64:23)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:29
From previous event:
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:12
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:651:10
    at H:\fancyguo-gm\server\node_modules\retry-as-promised\index.js:70:21
    at new Promise (<anonymous>)
    at retryAsPromised (H:\fancyguo-gm\server\node_modules\retry-as-promised\index.js:60:10)
    at H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:641:30
From previous event:
    at Sequelize.query (H:\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:590:23)
    at _callee5$ (H:\fancyguo-gm\server\src\app\service\/client.js:77:31)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at clientService.<anonymous> (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at clientService.stopClient (H:\fancyguo-gm\server\src\app\service\client.js:232:28)
    at _callee5$ (H:\fancyguo-gm\server\src\app\controllers\/client.js:42:39)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at stopClient (H:\fancyguo-gm\server\src\app\controllers\client.js:206:28)
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:45:18)
    at H:\fancyguo-gm\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at H:\fancyguo-gm\server\node_modules\koa-compose\index.js:36:12
    at dispatch (H:\fancyguo-gm\server\node_modules\koa-router\lib\router.js:351:31)
    at next (H:\fancyguo-gm\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at _callee$ (H:\fancyguo-gm\server\src\middleware\/index.js:48:11)
    at tryCatch (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at H:\fancyguo-gm\server\src\middleware\/index.js:43:2
*************** error log end ***************

