[2020-11-06T13:51:13.069] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/server/findServer
request client ip:  ::ffff:127.0.0.1
request query:  {"gameid":"13"}
response time: 1604641873068
err name: SequelizeDatabaseError
err message: column "undefined" does not exist
err stack: SequelizeDatabaseError: column "undefined" does not exist
    at Query.formatError (H:\致命代码\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at H:\致命代码\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
From previous event:
    at Query.run (H:\致命代码\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:64:23)
    at H:\致命代码\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:29
From previous event:
    at H:\致命代码\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:12
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at H:\致命代码\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:651:10
    at H:\致命代码\fancyguo-gm\server\node_modules\retry-as-promised\index.js:70:21
    at new Promise (<anonymous>)
    at retryAsPromised (H:\致命代码\fancyguo-gm\server\node_modules\retry-as-promised\index.js:60:10)
    at H:\致命代码\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:641:30
From previous event:
    at Sequelize.query (H:\致命代码\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:590:23)
    at GmServerService._callee$ (H:\致命代码\fancyguo-gm\server\src\app\service\/server.js:57:32)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at GmServerService.<anonymous> (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at GmServerService.serverFindByParam (H:\致命代码\fancyguo-gm\server\src\app\service\server.js:209:35)
    at _callee10$ (H:\致命代码\fancyguo-gm\server\src\app\controllers\/server.js:137:38)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at findServer (H:\致命代码\fancyguo-gm\server\src\app\controllers\server.js:455:28)
    at dispatch (H:\致命代码\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\致命代码\fancyguo-gm\server\node_modules\koa-compose\index.js:45:18)
    at H:\致命代码\fancyguo-gm\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (H:\致命代码\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at H:\致命代码\fancyguo-gm\server\node_modules\koa-compose\index.js:36:12
    at dispatch (H:\致命代码\fancyguo-gm\server\node_modules\koa-router\lib\router.js:351:31)
    at next (H:\致命代码\fancyguo-gm\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at _callee$ (H:\致命代码\fancyguo-gm\server\src\middleware\/index.js:47:11)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at H:\致命代码\fancyguo-gm\server\src\middleware\/index.js:42:2
*************** error log end ***************

[2020-11-06T14:01:28.222] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/server/serverCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"serverid":"45456456456","servername":"1123","serveridTrue":true,"plaform":["1"],"channel":["测试渠道"],"ip":"127.0.0.1:24024","display":"1","srttime":"2020-11-20T16:00:00.000Z","address":"","test":"0","page":1,"pagesize":20,"gameid":"13"}
response time: 1604642488221
err name: SequelizeDatabaseError
err message: column "servertrue" of relation "gm_server" does not exist
err stack: SequelizeDatabaseError: column "servertrue" of relation "gm_server" does not exist
    at Query.formatError (H:\致命代码\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at H:\致命代码\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
From previous event:
    at Query.run (H:\致命代码\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:64:23)
    at H:\致命代码\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:29
From previous event:
    at H:\致命代码\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:12
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at H:\致命代码\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:651:10
    at H:\致命代码\fancyguo-gm\server\node_modules\retry-as-promised\index.js:70:21
    at new Promise (<anonymous>)
    at retryAsPromised (H:\致命代码\fancyguo-gm\server\node_modules\retry-as-promised\index.js:60:10)
    at H:\致命代码\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:641:30
From previous event:
    at Sequelize.query (H:\致命代码\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:590:23)
    at GmServerService._callee4$ (H:\致命代码\fancyguo-gm\server\src\app\service\/server.js:171:31)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at GmServerService.<anonymous> (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at GmServerService.serverCreate (H:\致命代码\fancyguo-gm\server\src\app\service\server.js:406:30)
    at _callee9$ (H:\致命代码\fancyguo-gm\server\src\app\controllers\/server.js:124:38)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at serverCreate (H:\致命代码\fancyguo-gm\server\src\app\controllers\server.js:424:30)
    at dispatch (H:\致命代码\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\致命代码\fancyguo-gm\server\node_modules\koa-compose\index.js:45:18)
    at H:\致命代码\fancyguo-gm\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (H:\致命代码\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at H:\致命代码\fancyguo-gm\server\node_modules\koa-compose\index.js:36:12
    at dispatch (H:\致命代码\fancyguo-gm\server\node_modules\koa-router\lib\router.js:351:31)
    at next (H:\致命代码\fancyguo-gm\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at _callee$ (H:\致命代码\fancyguo-gm\server\src\middleware\/index.js:47:11)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at H:\致命代码\fancyguo-gm\server\src\middleware\/index.js:42:2
*************** error log end ***************

[2020-11-06T14:03:07.940] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/server/serverCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"serverid":"123123","servername":"112312","serveridTrue":true,"plaform":["1"],"channel":["测试渠道"],"ip":"","display":"1","srttime":"2020-11-17T16:00:00.000Z","address":"www.baidu.com","test":"0","page":1,"pagesize":20,"gameid":"13"}
response time: 1604642587939
err name: undefined
err message: 参数不合法
err stack: undefined
*************** error log end ***************

[2020-11-06T15:42:09.533] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/server/serverCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"serverid":"99981","servername":"sfsdfgsdfsd","serveridTrue":true,"plaform":["1"],"channel":["测试渠道"],"ip":"","display":"1","srttime":"2020-11-20T06:59:02.382Z","address":"s99981.mrhx.hz.37.com.cn","test":"0","page":1,"pagesize":20,"gameid":"13"}
response time: 1604648529533
err name: Error
err message: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1604648504700, end: 1604648526945. Message was: {
  module: 'server',
  server: 'createServer',
  args: { query: undefined, body: { id: 83 } }
}.
err stack: Error: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1604648504700, end: 1604648526945. Message was: {
  module: 'server',
  server: 'createServer',
  args: { query: undefined, body: { id: 83 } }
}.
    at Object.errormaker (H:\致命代码\fancyguo-gm\server\node_modules\eraro\eraro.js:112:15)
    at Object.act_tm [as ontm] (H:\致命代码\fancyguo-gm\server\node_modules\seneca\lib\act.js:86:32)
    at Timeout.timeout_check [as _onTimeout] (H:\致命代码\fancyguo-gm\server\node_modules\gate-executor\gate-executor.js:207:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
From previous event:
    at SenecaClient._callee$ (H:\致命代码\fancyguo-gm\server\src\xiaolu\/senecaclient.js:16:21)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at SenecaClient.<anonymous> (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at SenecaClient.get (H:\致命代码\fancyguo-gm\server\src\xiaolu\senecaclient.js:86:21)
    at GmServerService._callee4$ (H:\致命代码\fancyguo-gm\server\src\app\service\/server.js:184:40)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
*************** error log end ***************

[2020-11-06T15:42:32.146] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/server/serverCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"serverid":"99981","servername":"sfsdfgsdfsd41515","serveridTrue":true,"plaform":["1"],"channel":["测试渠道"],"ip":"","display":"1","srttime":"2020-11-20T06:59:02.382Z","address":"s99981.mrhx.hz.37.com.cn","test":"0","page":1,"pagesize":20,"gameid":"13"}
response time: 1604648552146
err name: undefined
err message: Cp交互失败,请确认IP地址
err stack: undefined
*************** error log end ***************

[2020-11-06T15:43:40.841] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/server/serverCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"serverid":"99981","servername":"sfsdfgsdfsd41515","serveridTrue":true,"plaform":["1"],"channel":["测试渠道"],"ip":"","display":"1","srttime":"2020-11-20T06:59:02.382Z","address":"s99981.mrhx.hz.37.com.cn","test":"0","page":1,"pagesize":20,"gameid":"13"}
response time: 1604648620841
err name: undefined
err message: Cp交互失败,请确认IP地址
err stack: undefined
*************** error log end ***************

[2020-11-06T15:43:53.504] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/server/serverCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"serverid":"99981","servername":"sfsdfgsdfsd41515","serveridTrue":true,"plaform":["1"],"channel":["测试渠道"],"ip":"","display":"1","srttime":"2020-11-20T06:59:02.382Z","address":"s99981.mrhx.hz.37.com.cn","test":"0","page":1,"pagesize":20,"gameid":"13"}
response time: 1604648633504
err name: undefined
err message: Cp交互失败,请确认IP地址
err stack: undefined
*************** error log end ***************

[2020-11-06T15:44:05.919] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/server/serverCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"serverid":"99981","servername":"sfsdfgsdfsd41515","serveridTrue":true,"plaform":["1"],"channel":["测试渠道"],"ip":"","display":"1","srttime":"2020-11-20T06:59:02.382Z","address":"s99981.mrhx.hz.37.com.cn","test":"0","page":1,"pagesize":20,"gameid":"13"}
response time: 1604648645919
err name: undefined
err message: Cp交互失败,请确认IP地址
err stack: undefined
*************** error log end ***************

[2020-11-06T15:46:21.090] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/server/serverCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"serverid":"","servername":"","serveridTrue":true,"plaform":[],"channel":[],"ip":"","display":"1","srttime":"","address":"","test":"0","page":1,"pagesize":20,"gameid":"13"}
response time: 1604648781090
err name: SequelizeDatabaseError
err message: invalid input syntax for type timestamp: "Invalid Date"
err stack: SequelizeDatabaseError: invalid input syntax for type timestamp: "Invalid Date"
    at Query.formatError (H:\致命代码\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at H:\致命代码\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
From previous event:
    at Query.run (H:\致命代码\fancyguo-gm\server\node_modules\sequelize\lib\dialects\postgres\query.js:64:23)
    at H:\致命代码\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:29
From previous event:
    at H:\致命代码\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:655:12
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at H:\致命代码\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:651:10
    at H:\致命代码\fancyguo-gm\server\node_modules\retry-as-promised\index.js:70:21
    at new Promise (<anonymous>)
    at retryAsPromised (H:\致命代码\fancyguo-gm\server\node_modules\retry-as-promised\index.js:60:10)
    at H:\致命代码\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:641:30
From previous event:
    at Sequelize.query (H:\致命代码\fancyguo-gm\server\node_modules\sequelize\lib\sequelize.js:590:23)
    at GmServerService._callee4$ (H:\致命代码\fancyguo-gm\server\src\app\service\/server.js:173:31)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at GmServerService.<anonymous> (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at GmServerService.serverCreate (H:\致命代码\fancyguo-gm\server\src\app\service\server.js:396:30)
    at _callee9$ (H:\致命代码\fancyguo-gm\server\src\app\controllers\/server.js:124:38)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at serverCreate (H:\致命代码\fancyguo-gm\server\src\app\controllers\server.js:424:30)
    at dispatch (H:\致命代码\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\致命代码\fancyguo-gm\server\node_modules\koa-compose\index.js:45:18)
    at H:\致命代码\fancyguo-gm\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (H:\致命代码\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at H:\致命代码\fancyguo-gm\server\node_modules\koa-compose\index.js:36:12
    at dispatch (H:\致命代码\fancyguo-gm\server\node_modules\koa-router\lib\router.js:351:31)
    at next (H:\致命代码\fancyguo-gm\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at _callee$ (H:\致命代码\fancyguo-gm\server\src\middleware\/index.js:47:11)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at H:\致命代码\fancyguo-gm\server\src\middleware\/index.js:42:2
*************** error log end ***************

[2020-11-06T15:50:00.101] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/server/serverCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"serverid":"99981","servername":"515","serveridTrue":true,"plaform":["1"],"channel":["测试渠道"],"ip":"","display":"1","srttime":"2020-11-20T07:48:30.424Z","address":"s99981.mrhx.hz.37.com.cn:4","test":"0","page":1,"pagesize":20,"gameid":"13"}
response time: 1604649000101
err name: Error
err message: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1604648975337, end: 1604648997650. Message was: {
  module: 'server',
  server: 'createServer',
  args: { query: undefined, body: { id: 92 } }
}.
err stack: Error: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1604648975337, end: 1604648997650. Message was: {
  module: 'server',
  server: 'createServer',
  args: { query: undefined, body: { id: 92 } }
}.
    at Object.errormaker (H:\致命代码\fancyguo-gm\server\node_modules\eraro\eraro.js:112:15)
    at Object.act_tm [as ontm] (H:\致命代码\fancyguo-gm\server\node_modules\seneca\lib\act.js:86:32)
    at Timeout.timeout_check [as _onTimeout] (H:\致命代码\fancyguo-gm\server\node_modules\gate-executor\gate-executor.js:207:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
From previous event:
    at SenecaClient._callee$ (H:\致命代码\fancyguo-gm\server\src\xiaolu\/senecaclient.js:16:21)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at SenecaClient.<anonymous> (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at SenecaClient.get (H:\致命代码\fancyguo-gm\server\src\xiaolu\senecaclient.js:86:21)
    at GmServerService._callee4$ (H:\致命代码\fancyguo-gm\server\src\app\service\/server.js:184:40)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
*************** error log end ***************

[2020-11-06T15:50:54.098] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/server/serverCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"serverid":"99981","servername":"515jg  hj","serveridTrue":true,"plaform":["1"],"channel":["测试渠道"],"ip":"","display":"1","srttime":"2020-11-20T07:48:30.424Z","address":"s99981.mrhx.hz.37.com.cn:4","test":"0","page":1,"pagesize":20,"gameid":"13"}
response time: 1604649054098
err name: Error
err message: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1604649029951, end: 1604649052282. Message was: {
  module: 'server',
  server: 'createServer',
  args: { query: undefined, body: { id: 93 } }
}.
err stack: Error: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1604649029951, end: 1604649052282. Message was: {
  module: 'server',
  server: 'createServer',
  args: { query: undefined, body: { id: 93 } }
}.
    at Object.errormaker (H:\致命代码\fancyguo-gm\server\node_modules\eraro\eraro.js:112:15)
    at Object.act_tm [as ontm] (H:\致命代码\fancyguo-gm\server\node_modules\seneca\lib\act.js:86:32)
    at Timeout.timeout_check [as _onTimeout] (H:\致命代码\fancyguo-gm\server\node_modules\gate-executor\gate-executor.js:207:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
From previous event:
    at SenecaClient._callee$ (H:\致命代码\fancyguo-gm\server\src\xiaolu\/senecaclient.js:16:21)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at SenecaClient.<anonymous> (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at SenecaClient.get (H:\致命代码\fancyguo-gm\server\src\xiaolu\senecaclient.js:86:21)
    at GmServerService._callee4$ (H:\致命代码\fancyguo-gm\server\src\app\service\/server.js:184:40)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
*************** error log end ***************

[2020-11-06T15:52:51.315] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/server/serverCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"serverid":"99981","servername":"asdasda","serveridTrue":true,"plaform":["1"],"channel":["测试渠道"],"ip":"","display":"1","srttime":"2020-11-20T07:48:30.424Z","address":"s99981.mrhx.hz.37.com.cn:4","test":"0","page":1,"pagesize":20,"gameid":"13"}
response time: 1604649171315
err name: Error
err message: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1604649145212, end: 1604649167437. Message was: {
  module: 'server',
  server: 'createServer',
  args: { query: undefined, body: { id: 94 } }
}.
err stack: Error: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1604649145212, end: 1604649167437. Message was: {
  module: 'server',
  server: 'createServer',
  args: { query: undefined, body: { id: 94 } }
}.
    at Object.errormaker (H:\致命代码\fancyguo-gm\server\node_modules\eraro\eraro.js:112:15)
    at Object.act_tm [as ontm] (H:\致命代码\fancyguo-gm\server\node_modules\seneca\lib\act.js:86:32)
    at Timeout.timeout_check [as _onTimeout] (H:\致命代码\fancyguo-gm\server\node_modules\gate-executor\gate-executor.js:207:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
From previous event:
    at SenecaClient._callee$ (H:\致命代码\fancyguo-gm\server\src\xiaolu\/senecaclient.js:16:21)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at SenecaClient.<anonymous> (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at SenecaClient.get (H:\致命代码\fancyguo-gm\server\src\xiaolu\senecaclient.js:86:21)
    at GmServerService._callee4$ (H:\致命代码\fancyguo-gm\server\src\app\service\/server.js:184:40)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
*************** error log end ***************

[2020-11-06T15:53:25.917] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/server/serverCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"serverid":"99981","servername":"asdasdaasd","serveridTrue":true,"plaform":["1"],"channel":["测试渠道"],"ip":"","display":"1","srttime":"2020-11-20T07:48:30.424Z","address":"s99981.mrhx.hz.37.com.cn:4","test":"0","page":1,"pagesize":20,"gameid":"13"}
response time: 1604649205917
err name: Error
err message: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1604649177292, end: 1604649199539. Message was: {
  module: 'server',
  server: 'createServer',
  args: { query: undefined, body: { id: 95 } }
}.
err stack: Error: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1604649177292, end: 1604649199539. Message was: {
  module: 'server',
  server: 'createServer',
  args: { query: undefined, body: { id: 95 } }
}.
    at Object.errormaker (H:\致命代码\fancyguo-gm\server\node_modules\eraro\eraro.js:112:15)
    at Object.act_tm [as ontm] (H:\致命代码\fancyguo-gm\server\node_modules\seneca\lib\act.js:86:32)
    at Timeout.timeout_check [as _onTimeout] (H:\致命代码\fancyguo-gm\server\node_modules\gate-executor\gate-executor.js:207:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
From previous event:
    at SenecaClient._callee$ (H:\致命代码\fancyguo-gm\server\src\xiaolu\/senecaclient.js:16:21)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at SenecaClient.<anonymous> (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at SenecaClient.get (H:\致命代码\fancyguo-gm\server\src\xiaolu\senecaclient.js:86:21)
    at GmServerService._callee4$ (H:\致命代码\fancyguo-gm\server\src\app\service\/server.js:184:40)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
*************** error log end ***************

[2020-11-06T15:54:08.482] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/server/serverCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"serverid":"99981","servername":"asdasdasdasdasd","serveridTrue":true,"plaform":["1"],"channel":["测试渠道"],"ip":"","display":"1","srttime":"2020-11-20T07:48:30.424Z","address":"s99981.mrhx.hz.37.com.cn:4","test":"0","page":1,"pagesize":20,"gameid":"13"}
response time: 1604649248482
err name: Error
err message: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1604649220800, end: 1604649243113. Message was: {
  module: 'server',
  server: 'createServer',
  args: { query: undefined, body: { id: 96 } }
}.
err stack: Error: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1604649220800, end: 1604649243113. Message was: {
  module: 'server',
  server: 'createServer',
  args: { query: undefined, body: { id: 96 } }
}.
    at Object.errormaker (H:\致命代码\fancyguo-gm\server\node_modules\eraro\eraro.js:112:15)
    at Object.act_tm [as ontm] (H:\致命代码\fancyguo-gm\server\node_modules\seneca\lib\act.js:86:32)
    at Timeout.timeout_check [as _onTimeout] (H:\致命代码\fancyguo-gm\server\node_modules\gate-executor\gate-executor.js:207:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
From previous event:
    at SenecaClient._callee$ (H:\致命代码\fancyguo-gm\server\src\xiaolu\/senecaclient.js:16:21)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at SenecaClient.<anonymous> (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at SenecaClient.get (H:\致命代码\fancyguo-gm\server\src\xiaolu\senecaclient.js:86:21)
    at GmServerService._callee4$ (H:\致命代码\fancyguo-gm\server\src\app\service\/server.js:184:40)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
*************** error log end ***************

[2020-11-06T15:55:13.562] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/server/serverCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"serverid":"99981","servername":"0s","serveridTrue":true,"plaform":["1"],"channel":["测试渠道"],"ip":"","display":"1","srttime":"2020-11-20T07:48:30.424Z","address":"s99981.mrhx.hz.37.com.cn:4","test":"0","page":1,"pagesize":20,"gameid":"13"}
response time: 1604649313562
err name: Error
err message: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1604649287589, end: 1604649309851. Message was: {
  module: 'server',
  server: 'createServer',
  args: { query: undefined, body: { id: 97 } }
}.
err stack: Error: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1604649287589, end: 1604649309851. Message was: {
  module: 'server',
  server: 'createServer',
  args: { query: undefined, body: { id: 97 } }
}.
    at Object.errormaker (H:\致命代码\fancyguo-gm\server\node_modules\eraro\eraro.js:112:15)
    at Object.act_tm [as ontm] (H:\致命代码\fancyguo-gm\server\node_modules\seneca\lib\act.js:86:32)
    at Timeout.timeout_check [as _onTimeout] (H:\致命代码\fancyguo-gm\server\node_modules\gate-executor\gate-executor.js:207:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
From previous event:
    at SenecaClient._callee$ (H:\致命代码\fancyguo-gm\server\src\xiaolu\/senecaclient.js:16:21)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at SenecaClient.<anonymous> (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at SenecaClient.get (H:\致命代码\fancyguo-gm\server\src\xiaolu\senecaclient.js:86:21)
    at GmServerService._callee4$ (H:\致命代码\fancyguo-gm\server\src\app\service\/server.js:184:40)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
*************** error log end ***************

[2020-11-06T15:56:40.239] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/server/serverCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"serverid":"99981","servername":"0s002","serveridTrue":true,"plaform":["1"],"channel":["测试渠道"],"ip":"","display":"1","srttime":"2020-11-20T07:48:30.424Z","address":"s99981.mrhx.hz.37.com.cn:4","test":"0","page":1,"pagesize":20,"gameid":"13"}
response time: 1604649400239
err name: Error
err message: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1604649376053, end: 1604649398375. Message was: {
  module: 'server',
  server: 'createServer',
  args: { query: undefined, body: { id: 98 } }
}.
err stack: Error: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1604649376053, end: 1604649398375. Message was: {
  module: 'server',
  server: 'createServer',
  args: { query: undefined, body: { id: 98 } }
}.
    at Object.errormaker (H:\致命代码\fancyguo-gm\server\node_modules\eraro\eraro.js:112:15)
    at Object.act_tm [as ontm] (H:\致命代码\fancyguo-gm\server\node_modules\seneca\lib\act.js:86:32)
    at Timeout.timeout_check [as _onTimeout] (H:\致命代码\fancyguo-gm\server\node_modules\gate-executor\gate-executor.js:207:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
From previous event:
    at SenecaClient._callee$ (H:\致命代码\fancyguo-gm\server\src\xiaolu\/senecaclient.js:16:21)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at SenecaClient.<anonymous> (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at SenecaClient.get (H:\致命代码\fancyguo-gm\server\src\xiaolu\senecaclient.js:86:21)
    at GmServerService._callee4$ (H:\致命代码\fancyguo-gm\server\src\app\service\/server.js:184:40)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
*************** error log end ***************

[2020-11-06T15:58:33.015] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/server/serverCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"serverid":"99981","servername":"0s002a","serveridTrue":true,"plaform":["1"],"channel":["测试渠道"],"ip":"","display":"1","srttime":"2020-11-20T07:48:30.424Z","address":"s99981.mrhx.hz.37.com.cn:4","test":"0","page":1,"pagesize":20,"gameid":"13"}
response time: 1604649513015
err name: Error
err message: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1604649489218, end: 1604649511529. Message was: {
  module: 'server',
  server: 'createServer',
  args: { query: undefined, body: { id: 99 } }
}.
err stack: Error: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1604649489218, end: 1604649511529. Message was: {
  module: 'server',
  server: 'createServer',
  args: { query: undefined, body: { id: 99 } }
}.
    at Object.errormaker (H:\致命代码\fancyguo-gm\server\node_modules\eraro\eraro.js:112:15)
    at Object.act_tm [as ontm] (H:\致命代码\fancyguo-gm\server\node_modules\seneca\lib\act.js:86:32)
    at Timeout.timeout_check [as _onTimeout] (H:\致命代码\fancyguo-gm\server\node_modules\gate-executor\gate-executor.js:207:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
From previous event:
    at SenecaClient._callee$ (H:\致命代码\fancyguo-gm\server\src\xiaolu\/senecaclient.js:16:21)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at SenecaClient.<anonymous> (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at SenecaClient.get (H:\致命代码\fancyguo-gm\server\src\xiaolu\senecaclient.js:86:21)
    at GmServerService._callee4$ (H:\致命代码\fancyguo-gm\server\src\app\service\/server.js:184:40)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
*************** error log end ***************

[2020-11-06T16:00:17.290] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/server/serverCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"serverid":"99981","servername":"0s002aa","serveridTrue":true,"plaform":["1"],"channel":["测试渠道"],"ip":"","display":"1","srttime":"2020-11-20T07:48:30.424Z","address":"s99981.mrhx.hz.37.com.cn:4","test":"0","page":1,"pagesize":20,"gameid":"13"}
response time: 1604649617290
err name: Error
err message: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1604649591544, end: 1604649613876. Message was: {
  module: 'server',
  server: 'createServer',
  args: { query: undefined, body: { id: 100 } }
}.
err stack: Error: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1604649591544, end: 1604649613876. Message was: {
  module: 'server',
  server: 'createServer',
  args: { query: undefined, body: { id: 100 } }
}.
    at Object.errormaker (H:\致命代码\fancyguo-gm\server\node_modules\eraro\eraro.js:112:15)
    at Object.act_tm [as ontm] (H:\致命代码\fancyguo-gm\server\node_modules\seneca\lib\act.js:86:32)
    at Timeout.timeout_check [as _onTimeout] (H:\致命代码\fancyguo-gm\server\node_modules\gate-executor\gate-executor.js:207:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
From previous event:
    at SenecaClient._callee$ (H:\致命代码\fancyguo-gm\server\src\xiaolu\/senecaclient.js:16:21)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at SenecaClient.<anonymous> (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at SenecaClient.get (H:\致命代码\fancyguo-gm\server\src\xiaolu\senecaclient.js:86:21)
    at GmServerService._callee4$ (H:\致命代码\fancyguo-gm\server\src\app\service\/server.js:184:40)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
*************** error log end ***************

[2020-11-06T16:00:47.354] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/server/serverCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"serverid":"99981","servername":"0s002aaa","serveridTrue":true,"plaform":["1"],"channel":["测试渠道"],"ip":"","display":"1","srttime":"2020-11-20T07:48:30.424Z","address":"s99981.mrhx.hz.37.com.cn:4","test":"0","page":1,"pagesize":20,"gameid":"13"}
response time: 1604649647354
err name: Error
err message: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1604649622417, end: 1604649644652. Message was: {
  module: 'server',
  server: 'createServer',
  args: { query: undefined, body: { id: 101 } }
}.
err stack: Error: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1604649622417, end: 1604649644652. Message was: {
  module: 'server',
  server: 'createServer',
  args: { query: undefined, body: { id: 101 } }
}.
    at Object.errormaker (H:\致命代码\fancyguo-gm\server\node_modules\eraro\eraro.js:112:15)
    at Object.act_tm [as ontm] (H:\致命代码\fancyguo-gm\server\node_modules\seneca\lib\act.js:86:32)
    at Timeout.timeout_check [as _onTimeout] (H:\致命代码\fancyguo-gm\server\node_modules\gate-executor\gate-executor.js:207:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
From previous event:
    at SenecaClient._callee$ (H:\致命代码\fancyguo-gm\server\src\xiaolu\/senecaclient.js:16:21)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at SenecaClient.<anonymous> (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at SenecaClient.get (H:\致命代码\fancyguo-gm\server\src\xiaolu\senecaclient.js:86:21)
    at GmServerService._callee4$ (H:\致命代码\fancyguo-gm\server\src\app\service\/server.js:184:40)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
*************** error log end ***************

[2020-11-06T16:01:50.852] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/server/serverCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"serverid":"99981","servername":"0s002aaa3","serveridTrue":true,"plaform":["1"],"channel":["测试渠道"],"ip":"","display":"1","srttime":"2020-11-20T07:48:30.424Z","address":"s99981.mrhx.hz.37.com.cn:4","test":"0","page":1,"pagesize":20,"gameid":"13"}
response time: 1604649710851
err name: Error
err message: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1604649687242, end: 1604649709544. Message was: {
  module: 'server',
  server: 'createServer',
  args: { query: undefined, body: { id: 102 } }
}.
err stack: Error: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1604649687242, end: 1604649709544. Message was: {
  module: 'server',
  server: 'createServer',
  args: { query: undefined, body: { id: 102 } }
}.
    at Object.errormaker (H:\致命代码\fancyguo-gm\server\node_modules\eraro\eraro.js:112:15)
    at Object.act_tm [as ontm] (H:\致命代码\fancyguo-gm\server\node_modules\seneca\lib\act.js:86:32)
    at Timeout.timeout_check [as _onTimeout] (H:\致命代码\fancyguo-gm\server\node_modules\gate-executor\gate-executor.js:207:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
From previous event:
    at SenecaClient._callee$ (H:\致命代码\fancyguo-gm\server\src\xiaolu\/senecaclient.js:16:21)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at SenecaClient.<anonymous> (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at SenecaClient.get (H:\致命代码\fancyguo-gm\server\src\xiaolu\senecaclient.js:86:21)
    at GmServerService._callee4$ (H:\致命代码\fancyguo-gm\server\src\app\service\/server.js:184:40)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
*************** error log end ***************

[2020-11-06T16:03:23.406] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/server/serverCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"serverid":"99981","servername":"0s002aaa3a","serveridTrue":true,"plaform":["1"],"channel":["测试渠道"],"ip":"","display":"1","srttime":"2020-11-20T07:48:30.424Z","address":"s99981.mrhx.hz.37.com.cn:4","test":"0","page":1,"pagesize":20,"gameid":"13"}
response time: 1604649803405
err name: Error
err message: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1604649779241, end: 1604649801465. Message was: {
  module: 'server',
  server: 'createServer',
  args: { query: undefined, body: { id: 103 } }
}.
err stack: Error: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1604649779241, end: 1604649801465. Message was: {
  module: 'server',
  server: 'createServer',
  args: { query: undefined, body: { id: 103 } }
}.
    at Object.errormaker (H:\致命代码\fancyguo-gm\server\node_modules\eraro\eraro.js:112:15)
    at Object.act_tm [as ontm] (H:\致命代码\fancyguo-gm\server\node_modules\seneca\lib\act.js:86:32)
    at Timeout.timeout_check [as _onTimeout] (H:\致命代码\fancyguo-gm\server\node_modules\gate-executor\gate-executor.js:207:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
From previous event:
    at SenecaClient._callee$ (H:\致命代码\fancyguo-gm\server\src\xiaolu\/senecaclient.js:16:21)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at SenecaClient.<anonymous> (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at SenecaClient.get (H:\致命代码\fancyguo-gm\server\src\xiaolu\senecaclient.js:86:21)
    at GmServerService._callee4$ (H:\致命代码\fancyguo-gm\server\src\app\service\/server.js:184:40)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
*************** error log end ***************

[2020-11-06T16:05:00.753] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/server/serverCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"serverid":"99981","servername":"0s002aaa3aa","serveridTrue":true,"plaform":["1"],"channel":["测试渠道"],"ip":"","display":"1","srttime":"2020-11-20T07:48:30.424Z","address":"s99981.mrhx.hz.37.com.cn:4","test":"0","page":1,"pagesize":20,"gameid":"13"}
response time: 1604649900752
err name: undefined
err message: Cp交互失败,请确认IP地址
err stack: undefined
*************** error log end ***************

