[2020-10-22T11:16:15.907] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/announcement/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"bulletinid":"","stime":"","etime":"","plaform":"1","channel":"","servername":"","interval":"","weights":"","title":"1","a":"1","text":"1","range":"1","type":"2","gameid":"1"}
response time: 1603336575906
err name: ReferenceError
err message: fileWebUrl is not defined
err stack: ReferenceError: fileWebUrl is not defined
    at _callee3$ (H:\致命代码\fancyguo-gm\server\src\app\service\/gm-announcement.js:99:69)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
*************** error log end ***************

[2020-10-22T16:11:35.069] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/mail/postMailToCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"title":"1","text":"1","allServerTrue":true,"roleId":"","sendTime":true,"mailLink":"1","plaform":"","channel":"","serverName":["王者测试服"],"carryAnnex":false,"sendDateTime":"","smtpId":"112128","gameid":"1"}
response time: 1603354295068
err name: Error
err message: connect ECONNREFUSED 127.0.0.1:5000
err stack: Error: connect ECONNREFUSED 127.0.0.1:5000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
*************** error log end ***************

[2020-10-22T16:14:04.350] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/mail/postMailToCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"title":"1","text":"1","allServerTrue":true,"roleId":"","sendTime":true,"mailLink":"1","plaform":"","channel":"","serverName":["王者测试服"],"carryAnnex":false,"sendDateTime":"","smtpId":"112128","gameid":"1"}
response time: 1603354444349
err name: TypeError
err message: this.SenClient is not a function
err stack: TypeError: this.SenClient is not a function
    at MailService._callee9$ (H:\致命代码\fancyguo-gm\server\src\app\service\/mail.js:220:24)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at MailService.<anonymous> (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at MailService.mailSendTimely (H:\致命代码\fancyguo-gm\server\src\app\service\mail.js:539:32)
    at MailService._callee6$ (H:\致命代码\fancyguo-gm\server\src\app\service\/mail.js:192:16)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
*************** error log end ***************

[2020-10-22T16:14:42.310] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/mail/postMailToCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"title":"1","text":"1","allServerTrue":true,"roleId":"","sendTime":true,"mailLink":"1","plaform":"","channel":"","serverName":["王者测试服"],"carryAnnex":false,"sendDateTime":"","smtpId":"143330","gameid":"1"}
response time: 1603354482310
err name: Error
err message: seneca: No matching action pattern found for {  module: 'mail',  mail: 'immediate',  args: { body: { gameid: '1', id: 31 } }}, and no default result provided (using a default$ property).
err stack: Error: seneca: No matching action pattern found for {  module: 'mail',  mail: 'immediate',  args: { body: { gameid: '1', id: 31 } }}, and no default result provided (using a default$ property).
    at module.exports.internals.Utils.internals.Utils.handle_response (H:\致命代码\fancyguo-gm\server\node_modules\seneca-transport\lib\transport-utils.js:77:11)
    at Duplex.messager._write (H:\致命代码\fancyguo-gm\server\node_modules\seneca-transport\lib\tcp.js:240:19)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Duplex.Writable.write (_stream_writable.js:318:11)
    at DestroyableTransform.ondata (H:\致命代码\fancyguo-gm\server\node_modules\readable-stream\lib\_stream_readable.js:619:20)
    at DestroyableTransform.emit (events.js:315:20)
    at addChunk (H:\致命代码\fancyguo-gm\server\node_modules\readable-stream\lib\_stream_readable.js:291:12)
    at readableAddChunk (H:\致命代码\fancyguo-gm\server\node_modules\readable-stream\lib\_stream_readable.js:278:11)
    at DestroyableTransform.Readable.push (H:\致命代码\fancyguo-gm\server\node_modules\readable-stream\lib\_stream_readable.js:245:10)
    at DestroyableTransform.Transform.push (H:\致命代码\fancyguo-gm\server\node_modules\readable-stream\lib\_stream_transform.js:148:32)
    at push (H:\致命代码\fancyguo-gm\server\node_modules\split2\index.js:52:10)
    at DestroyableTransform.transform [as _transform] (H:\致命代码\fancyguo-gm\server\node_modules\split2\index.js:33:5)
    at DestroyableTransform.Transform._read (H:\致命代码\fancyguo-gm\server\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (H:\致命代码\fancyguo-gm\server\node_modules\readable-stream\lib\_stream_transform.js:172:83)
    at doWrite (H:\致命代码\fancyguo-gm\server\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (H:\致命代码\fancyguo-gm\server\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (H:\致命代码\fancyguo-gm\server\node_modules\readable-stream\lib\_stream_writable.js:334:11)
    at Socket.ondata (_stream_readable.js:717:22)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
From previous event:
    at SenecaClient._callee$ (H:\致命代码\fancyguo-gm\server\src\xiaolu\/senecaclient.js:16:21)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at SenecaClient.<anonymous> (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at SenecaClient.get (H:\致命代码\fancyguo-gm\server\src\xiaolu\senecaclient.js:86:21)
    at MailService._callee9$ (H:\致命代码\fancyguo-gm\server\src\app\service\/mail.js:220:34)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at MailService.<anonymous> (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at MailService.mailSendTimely (H:\致命代码\fancyguo-gm\server\src\app\service\mail.js:539:32)
    at MailService._callee6$ (H:\致命代码\fancyguo-gm\server\src\app\service\/mail.js:192:16)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
*************** error log end ***************

[2020-10-22T16:15:33.199] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/mail/postMailToCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"title":"1","text":"1","allServerTrue":true,"roleId":"","sendTime":true,"mailLink":"1","plaform":"","channel":"","serverName":["王者测试服"],"carryAnnex":false,"sendDateTime":"","smtpId":"143330","gameid":"1"}
response time: 1603354533199
err name: Error
err message: 邮件及时发送 失败
err stack: Error: 邮件及时发送 失败
    at MailService._callee9$ (H:\致命代码\fancyguo-gm\server\src\app\service\/mail.js:224:9)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
*************** error log end ***************

[2020-10-22T16:16:01.326] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/mail/postMailToCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"title":"1","text":"1","allServerTrue":true,"roleId":"","sendTime":true,"mailLink":"1","plaform":"","channel":"","serverName":["王者测试服"],"carryAnnex":false,"sendDateTime":"","smtpId":"143330","gameid":"1"}
response time: 1603354561325
err name: Error
err message: 邮件及时发送 失败
err stack: Error: 邮件及时发送 失败
    at MailService._callee9$ (H:\致命代码\fancyguo-gm\server\src\app\service\/mail.js:225:9)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
*************** error log end ***************

[2020-10-22T16:16:48.447] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/mail/postMailToCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"title":"1","text":"1","allServerTrue":true,"roleId":"","sendTime":true,"mailLink":"1","plaform":"","channel":"","serverName":["王者测试服"],"carryAnnex":false,"sendDateTime":"","smtpId":"143330","gameid":"1"}
response time: 1603354608447
err name: Error
err message: 邮件及时发送 失败
err stack: Error: 邮件及时发送 失败
    at MailService._callee9$ (H:\致命代码\fancyguo-gm\server\src\app\service\/mail.js:225:9)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
*************** error log end ***************

[2020-10-22T16:21:42.640] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/mail/postMailToCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"title":"1","text":"1","allServerTrue":true,"roleId":"","sendTime":true,"mailLink":"1","plaform":"","channel":"","serverName":["王者测试服"],"carryAnnex":false,"sendDateTime":"","smtpId":"143330","gameid":"1"}
response time: 1603354902640
err name: Error
err message: 邮件及时发送 失败
err stack: Error: 邮件及时发送 失败
    at MailService._callee9$ (H:\致命代码\fancyguo-gm\server\src\app\service\/mail.js:225:9)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
*************** error log end ***************

[2020-10-22T16:23:27.642] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/mail/postMailToCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"title":"1","text":"1","allServerTrue":true,"roleId":"","sendTime":true,"mailLink":"1","plaform":"","channel":"","serverName":["王者测试服"],"carryAnnex":false,"sendDateTime":"","smtpId":"143330","gameid":"1"}
response time: 1603355007642
err name: Error
err message: 邮件及时发送 失败
err stack: Error: 邮件及时发送 失败
    at MailService._callee9$ (H:\致命代码\fancyguo-gm\server\src\app\service\/mail.js:225:9)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
*************** error log end ***************

[2020-10-22T16:24:16.114] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/mail/postMailToCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"title":"1","text":"1","allServerTrue":true,"roleId":"","sendTime":true,"mailLink":"1","plaform":"","channel":"","serverName":["王者测试服"],"carryAnnex":false,"sendDateTime":"","smtpId":"143330","gameid":"1"}
response time: 1603355056114
err name: Error
err message: 邮件及时发送 失败
err stack: Error: 邮件及时发送 失败
    at MailService._callee9$ (H:\致命代码\fancyguo-gm\server\src\app\service\/mail.js:225:9)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
*************** error log end ***************

[2020-10-22T16:26:40.728] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/mail/postMailToCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"title":"1","text":"1","allServerTrue":true,"roleId":"","sendTime":true,"mailLink":"1","plaform":"","channel":"","serverName":["王者测试服"],"carryAnnex":false,"sendDateTime":"","smtpId":"143330","gameid":"1"}
response time: 1603355200728
err name: Error
err message: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1603355176362, end: 1603355198588. Message was: {
  module: 'mail',
  mail: 'immediate',
  args: { query: undefined, body: { gameid: '1', id: 38 } }
}.
err stack: Error: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1603355176362, end: 1603355198588. Message was: {
  module: 'mail',
  mail: 'immediate',
  args: { query: undefined, body: { gameid: '1', id: 38 } }
}.
    at Object.errormaker (H:\致命代码\fancyguo-gm\server\node_modules\eraro\eraro.js:112:15)
    at Object.act_tm [as ontm] (H:\致命代码\fancyguo-gm\server\node_modules\seneca\lib\act.js:86:32)
    at Timeout.timeout_check [as _onTimeout] (H:\致命代码\fancyguo-gm\server\node_modules\gate-executor\gate-executor.js:207:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
From previous event:
    at SenecaClient._callee$ (H:\致命代码\fancyguo-gm\server\src\xiaolu\/senecaclient.js:16:21)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at SenecaClient.<anonymous> (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at SenecaClient.get (H:\致命代码\fancyguo-gm\server\src\xiaolu\senecaclient.js:86:21)
    at MailService._callee9$ (H:\致命代码\fancyguo-gm\server\src\app\service\/mail.js:219:34)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at MailService.<anonymous> (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at MailService.mailSendTimely (H:\致命代码\fancyguo-gm\server\src\app\service\mail.js:538:32)
    at MailService._callee6$ (H:\致命代码\fancyguo-gm\server\src\app\service\/mail.js:192:16)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
*************** error log end ***************

[2020-10-22T17:16:06.754] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/mail/postMailToCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"title":"1","text":"1","allServerTrue":true,"roleId":"","mailLink":"2","plaform":"","channel":"","serverName":["王者测试服"],"carryAnnex":false,"sendTime":false,"smtpId":"155444","sendDateTime":"2020-10-30T16:00:00.000Z","gameid":"1"}
response time: 1603358166754
err name: Error
err message: connect ECONNREFUSED 127.0.0.1:5000
err stack: Error: connect ECONNREFUSED 127.0.0.1:5000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
*************** error log end ***************

[2020-10-22T17:19:12.272] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/mail/postMailToCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"title":"1","text":"1","allServerTrue":true,"roleId":"","mailLink":"2","plaform":"","channel":"","serverName":["王者测试服"],"carryAnnex":false,"sendTime":false,"smtpId":"155444","sendDateTime":"2020-10-30T16:00:00.000Z","gameid":"1"}
response time: 1603358352271
err name: Error
err message: 邮件定时发送 失败
err stack: Error: 邮件定时发送 失败
    at MailService._callee10$ (H:\致命代码\fancyguo-gm\server\src\app\service\/mail.js:235:9)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
*************** error log end ***************

[2020-10-22T17:19:43.980] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/mail/postMailToCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"title":"1","text":"1","allServerTrue":true,"roleId":"","mailLink":"2","plaform":"","channel":"","serverName":["王者测试服"],"carryAnnex":false,"sendTime":false,"smtpId":"155444","sendDateTime":"2020-10-30T16:00:00.000Z","gameid":"1"}
response time: 1603358383979
err name: Error
err message: 邮件定时发送 失败
err stack: Error: 邮件定时发送 失败
    at MailService._callee10$ (H:\致命代码\fancyguo-gm\server\src\app\service\/mail.js:236:9)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
*************** error log end ***************

[2020-10-22T20:19:53.589] [ERROR] errorLogger - 
*************** error log start ***************
request method: PUT
request originalUrl:  /api/announcement/update?id=111&status=1&anno_status=%E5%BE%85%E7%94%A8&title=2&game_id=1&text=1&link=3&stime=&etime=&type=%E5%85%AC%E5%91%8A%E6%9D%BF&plaforms[]=%E5%AE%89%E5%8D%93&changeshow=true&stopshow=true
request client ip:  ::ffff:127.0.0.1
request body: 
{"gameid":"1"}
response time: 1603369193589
err name: Error
err message: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1603369168540, end: 1603369190859. Message was: {
  module: 'anno',
  anno: 'stop',
  args: { query: undefined, body: { id: 111 } }
}.
err stack: Error: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1603369168540, end: 1603369190859. Message was: {
  module: 'anno',
  anno: 'stop',
  args: { query: undefined, body: { id: 111 } }
}.
    at Object.errormaker (H:\致命代码\fancyguo-gm\server\node_modules\eraro\eraro.js:112:15)
    at Object.act_tm [as ontm] (H:\致命代码\fancyguo-gm\server\node_modules\seneca\lib\act.js:86:32)
    at Timeout.timeout_check [as _onTimeout] (H:\致命代码\fancyguo-gm\server\node_modules\gate-executor\gate-executor.js:207:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
From previous event:
    at SenecaClient._callee$ (H:\致命代码\fancyguo-gm\server\src\xiaolu\/senecaclient.js:16:21)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at SenecaClient.<anonymous> (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at SenecaClient.get (H:\致命代码\fancyguo-gm\server\src\xiaolu\senecaclient.js:86:21)
    at GmAnnouncementService._callee5$ (H:\致命代码\fancyguo-gm\server\src\app\service\/gm-announcement.js:150:24)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
*************** error log end ***************

[2020-10-22T20:19:54.031] [ERROR] errorLogger - 
*************** error log start ***************
request method: PUT
request originalUrl:  /api/announcement/update?id=112&status=1&anno_status=%E5%BE%85%E7%94%A8&title=3&game_id=1&text=2&link=1&stime=&etime=&type=%E5%85%AC%E5%91%8A%E6%9D%BF&plaforms[]=%E5%AE%89%E5%8D%93&changeshow=true&stopshow=true
request client ip:  ::ffff:127.0.0.1
request body: 
{"gameid":"1"}
response time: 1603369194031
err name: Error
err message: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1603369170254, end: 1603369193590. Message was: {
  module: 'anno',
  anno: 'stop',
  args: { query: undefined, body: { id: 112 } }
}.
err stack: Error: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1603369170254, end: 1603369193590. Message was: {
  module: 'anno',
  anno: 'stop',
  args: { query: undefined, body: { id: 112 } }
}.
    at Object.errormaker (H:\致命代码\fancyguo-gm\server\node_modules\eraro\eraro.js:112:15)
    at Object.act_tm [as ontm] (H:\致命代码\fancyguo-gm\server\node_modules\seneca\lib\act.js:86:32)
    at Timeout.timeout_check [as _onTimeout] (H:\致命代码\fancyguo-gm\server\node_modules\gate-executor\gate-executor.js:207:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
From previous event:
    at SenecaClient._callee$ (H:\致命代码\fancyguo-gm\server\src\xiaolu\/senecaclient.js:16:21)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at SenecaClient.<anonymous> (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at SenecaClient.get (H:\致命代码\fancyguo-gm\server\src\xiaolu\senecaclient.js:86:21)
    at GmAnnouncementService._callee5$ (H:\致命代码\fancyguo-gm\server\src\app\service\/gm-announcement.js:150:24)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
*************** error log end ***************

[2020-10-22T20:19:57.387] [ERROR] errorLogger - 
*************** error log start ***************
request method: PUT
request originalUrl:  /api/announcement/update?id=111&status=1&anno_status=%E5%BE%85%E7%94%A8&title=2&game_id=1&text=1&link=3&stime=&etime=&type=%E5%85%AC%E5%91%8A%E6%9D%BF&plaforms[]=%E5%AE%89%E5%8D%93&changeshow=true&stopshow=true
request client ip:  ::ffff:127.0.0.1
request body: 
{"gameid":"1"}
response time: 1603369197387
err name: Error
err message: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1603369173519, end: 1603369195817. Message was: {
  module: 'anno',
  anno: 'stop',
  args: { query: undefined, body: { id: 111 } }
}.
err stack: Error: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1603369173519, end: 1603369195817. Message was: {
  module: 'anno',
  anno: 'stop',
  args: { query: undefined, body: { id: 111 } }
}.
    at Object.errormaker (H:\致命代码\fancyguo-gm\server\node_modules\eraro\eraro.js:112:15)
    at Object.act_tm [as ontm] (H:\致命代码\fancyguo-gm\server\node_modules\seneca\lib\act.js:86:32)
    at Timeout.timeout_check [as _onTimeout] (H:\致命代码\fancyguo-gm\server\node_modules\gate-executor\gate-executor.js:207:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
From previous event:
    at SenecaClient._callee$ (H:\致命代码\fancyguo-gm\server\src\xiaolu\/senecaclient.js:16:21)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at SenecaClient.<anonymous> (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at SenecaClient.get (H:\致命代码\fancyguo-gm\server\src\xiaolu\senecaclient.js:86:21)
    at GmAnnouncementService._callee5$ (H:\致命代码\fancyguo-gm\server\src\app\service\/gm-announcement.js:150:24)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
*************** error log end ***************

[2020-10-22T20:29:17.261] [ERROR] errorLogger - 
*************** error log start ***************
request method: PUT
request originalUrl:  /api/announcement/update?id=115&status=1&end_time=2020-10-30T16:00:00.000Z&start_time=2020-10-29T16:00:00.000Z&anno_status=%E5%8F%91%E5%B8%83%E4%B8%AD&game_id=1&time_interval=1&weights=1&stime=2020-10-30+00:00:00&etime=2020-10-31+00:00:00&type=%E8%B7%91%E9%A9%AC%E7%81%AF&plaforms[]=%E5%AE%89%E5%8D%93&changeshow=false&stopshow=true
request client ip:  ::ffff:127.0.0.1
request body: 
{"gameid":"1"}
response time: 1603369757260
err name: TypeError
err message: Cannot read property 'id' of undefined
err stack: TypeError: Cannot read property 'id' of undefined
    at _callee3$ (H:\致命代码\fancyguo-gm\server\src\app\controllers\/gm-announcement.js:44:50)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at update (H:\致命代码\fancyguo-gm\server\src\app\controllers\gm-announcement.js:175:24)
    at dispatch (H:\致命代码\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\致命代码\fancyguo-gm\server\node_modules\koa-compose\index.js:45:18)
    at H:\致命代码\fancyguo-gm\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (H:\致命代码\fancyguo-gm\server\node_modules\koa-compose\index.js:44:32)
    at H:\致命代码\fancyguo-gm\server\node_modules\koa-compose\index.js:36:12
    at dispatch (H:\致命代码\fancyguo-gm\server\node_modules\koa-router\lib\router.js:351:31)
    at next (H:\致命代码\fancyguo-gm\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at _callee$ (H:\致命代码\fancyguo-gm\server\src\middleware\/index.js:47:11)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at H:\致命代码\fancyguo-gm\server\src\middleware\/index.js:42:2
    at dispatch (H:\致命代码\fancyguo-gm\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at H:\致命代码\fancyguo-gm\server\node_modules\koa-mount\index.js:52:32
    at next (H:\致命代码\fancyguo-gm\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at _callee$ (H:\致命代码\fancyguo-gm\server\src\middleware\/auth.js:88:9)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
*************** error log end ***************

[2020-10-22T20:35:48.358] [ERROR] errorLogger - 
*************** error log start ***************
request method: PUT
request originalUrl:  /api/announcement/update?id=119&status=1&anno_status=%E5%8F%91%E5%B8%83%E4%B8%AD&title=123&game_id=1&text=123&link=123&sendtime=2020-10-22T12:33:24.000Z&stime=2020-10-22+20:33:24&etime=2020-10-30+00:00:00&type=%E5%85%AC%E5%91%8A%E6%9D%BF&plaforms[]=%E5%AE%89%E5%8D%93&changeshow=false&stopshow=true
request client ip:  
request body: 
{"gameid":"1"}
response time: 1603370148358
err name: Error
err message: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1603370125497, end: 1603370147798. Message was: {
  module: 'anno',
  anno: 'stop',
  args: { query: undefined, body: { id: 119 } }
}.
err stack: Error: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1603370125497, end: 1603370147798. Message was: {
  module: 'anno',
  anno: 'stop',
  args: { query: undefined, body: { id: 119 } }
}.
    at Object.errormaker (H:\致命代码\fancyguo-gm\server\node_modules\eraro\eraro.js:112:15)
    at Object.act_tm [as ontm] (H:\致命代码\fancyguo-gm\server\node_modules\seneca\lib\act.js:86:32)
    at Timeout.timeout_check [as _onTimeout] (H:\致命代码\fancyguo-gm\server\node_modules\gate-executor\gate-executor.js:207:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
From previous event:
    at SenecaClient._callee$ (H:\致命代码\fancyguo-gm\server\src\xiaolu\/senecaclient.js:16:21)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at SenecaClient.<anonymous> (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at SenecaClient.get (H:\致命代码\fancyguo-gm\server\src\xiaolu\senecaclient.js:86:21)
    at GmAnnouncementService._callee5$ (H:\致命代码\fancyguo-gm\server\src\app\service\/gm-announcement.js:152:25)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
*************** error log end ***************

[2020-10-22T20:58:58.511] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/white/mailCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"title":"1","text":"2","sendType":true,"cycle":"month","annex":[{"annexName":["特殊道具","9001"],"annexNumber":"2","id":0}],"gameid":"1"}
response time: 1603371538510
err name: ReferenceError
err message: id is not defined
err stack: ReferenceError: id is not defined
    at _callee$ (H:\致命代码\fancyguo-gm\server\src\app\controllers\/white.js:15:46)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
*************** error log end ***************

