[2020-11-02T17:29:20.458] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/mail/postMailToCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"title":"1","text":"1","allServerTrue":true,"roleId":"","sendTime":true,"mailLink":"2","plaform":"","channel":"","serverName":["测试区服","测试区服四服","测试机一","测试区服三服","测试机一机","测试机二","测试区服二服","测试区服一服"],"carryAnnex":true,"sendDateTime":"","smtpId":"2961","Annex":["{\"ID\":\"9001\",\"name\":\"特殊道具\",\"number\":\"231\"}","{\"ID\":\"17002\",\"name\":\"文物\",\"number\":\"11\"}"],"gameid":"1"}
response time: 1604309360457
err name: Error
err message: 邮件及时发送 失败
err stack: Error: 邮件及时发送 失败
    at MailService._callee9$ (H:\致命代码\fancyguo-gm\server\src\app\service\/mail.js:225:9)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
*************** error log end ***************

[2020-11-02T17:39:59.255] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/mail/postMailToCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"title":"1","text":"1","allServerTrue":true,"roleId":"","sendTime":true,"mailLink":"2","plaform":"","channel":"","serverName":["测试区服","测试区服四服","测试机一","测试区服三服","测试机一机","测试机二","测试区服二服","测试区服一服"],"carryAnnex":true,"sendDateTime":"","smtpId":"2961","Annex":["{\"ID\":\"9001\",\"name\":\"特殊道具\",\"number\":\"231\"}","{\"ID\":\"17002\",\"name\":\"文物\",\"number\":\"11\"}"],"gameid":"1"}
response time: 1604309999254
err name: Error
err message: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1604309973478, end: 1604309995739. Message was: {
  module: 'mail',
  mail: 'immediate',
  args: { query: undefined, body: { gameid: '1', id: 53 } }
}.
err stack: Error: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1604309973478, end: 1604309995739. Message was: {
  module: 'mail',
  mail: 'immediate',
  args: { query: undefined, body: { gameid: '1', id: 53 } }
}.
    at Object.errormaker (H:\致命代码\fancyguo-gm\server\node_modules\eraro\eraro.js:112:15)
    at Object.act_tm [as ontm] (H:\致命代码\fancyguo-gm\server\node_modules\seneca\lib\act.js:86:32)
    at Timeout.timeout_check [as _onTimeout] (H:\致命代码\fancyguo-gm\server\node_modules\gate-executor\gate-executor.js:207:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
From previous event:
    at SenecaClient._callee$ (H:\致命代码\fancyguo-gm\server\src\xiaolu\/senecaclient.js:16:21)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at SenecaClient.<anonymous> (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at SenecaClient.get (H:\致命代码\fancyguo-gm\server\src\xiaolu\senecaclient.js:86:21)
    at MailService._callee9$ (H:\致命代码\fancyguo-gm\server\src\app\service\/mail.js:219:34)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at MailService.<anonymous> (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at MailService.mailSendTimely (H:\致命代码\fancyguo-gm\server\src\app\service\mail.js:538:32)
    at MailService._callee6$ (H:\致命代码\fancyguo-gm\server\src\app\service\/mail.js:192:16)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
*************** error log end ***************

[2020-11-02T17:41:30.003] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/mail/postMailToCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"title":"1","text":"1","allServerTrue":true,"roleId":"","sendTime":true,"mailLink":"2","plaform":"","channel":"","serverName":["测试区服","测试区服四服","测试机一","测试区服三服","测试机一机","测试机二","测试区服二服","测试区服一服"],"carryAnnex":true,"sendDateTime":"","smtpId":"2961","Annex":["{\"ID\":\"9001\",\"name\":\"特殊道具\",\"number\":\"231\"}","{\"ID\":\"17002\",\"name\":\"文物\",\"number\":\"11\"}"],"gameid":"1"}
response time: 1604310090003
err name: Error
err message: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1604310064259, end: 1604310086546. Message was: {
  module: 'mail',
  mail: 'immediate',
  args: { query: undefined, body: { gameid: '1', id: 54 } }
}.
err stack: Error: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1604310064259, end: 1604310086546. Message was: {
  module: 'mail',
  mail: 'immediate',
  args: { query: undefined, body: { gameid: '1', id: 54 } }
}.
    at Object.errormaker (H:\致命代码\fancyguo-gm\server\node_modules\eraro\eraro.js:112:15)
    at Object.act_tm [as ontm] (H:\致命代码\fancyguo-gm\server\node_modules\seneca\lib\act.js:86:32)
    at Timeout.timeout_check [as _onTimeout] (H:\致命代码\fancyguo-gm\server\node_modules\gate-executor\gate-executor.js:207:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
From previous event:
    at SenecaClient._callee$ (H:\致命代码\fancyguo-gm\server\src\xiaolu\/senecaclient.js:16:21)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at SenecaClient.<anonymous> (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at SenecaClient.get (H:\致命代码\fancyguo-gm\server\src\xiaolu\senecaclient.js:86:21)
    at MailService._callee9$ (H:\致命代码\fancyguo-gm\server\src\app\service\/mail.js:219:34)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at MailService.<anonymous> (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at MailService.mailSendTimely (H:\致命代码\fancyguo-gm\server\src\app\service\mail.js:538:32)
    at MailService._callee6$ (H:\致命代码\fancyguo-gm\server\src\app\service\/mail.js:192:16)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
*************** error log end ***************

